YBEMiniProjectTeam/MINI-Front

src/main.tsx

Add: ChakraProvider

---

src/api/login/LoginApi.ts
src/api/register/RegisterApi.ts
src/components/AgreementModal/AgreementModalForm.tsx
src/components/AgreementModal/AgreementModalStyles.ts
src/components/Login/Login.types.ts
src/components/Login/LoginForm.tsx
src/components/Login/LoginStyles.ts
src/components/Register/Register.types.ts
src/components/Register/RegisterForm.tsx
src/components/Register/RegisterStyles.ts
src/components/Register/validators.ts
src/pages/login/Login.tsx
src/pages/register/Register.tsx

Close #8 
로그인 회원가입 기능, 약관동의 모달 구현 #8
로그인 페이지 , 컴포넌트, 스타일 생성 및 로직 구현
회원가입 페이지 , 컴포넌트, 스타일 생성 및 로직 구현
약관동의 모달 컴포넌트, 스타일 생성
부모 컴포넌트에서 해당 State 생성 후 props로 내려주기
isAgreement : 동의 여부 ( 동의를 할 시 true )
isShowModal : 모달창 여부 ( 보일 시 true )
```js
// 부모컴포넌트.tsx
const [isAgreement, setIsAgreement] = useState(false);
const [isShowModal, setIsShowModal] = useState(false);
//
...
//
return ( {
isShowModal ? (
<AgreementModalForm
setIsAgreement={setIsAgreement}
setIsShowModal={setIsShowModal}
></AgreementModalForm>
) : null} )
)
```
전반적인 코드 및 파일명이 잘 되었는지 확인 부탁드립니다.

로그인 회원가입 기능, 약관동의 모달 구현 #8

---

package-lock.json
package.json
src/components/ChooseRegionModal/ChooseRegionModal.styles.ts
src/components/ChooseRegionModal/ChooseRegionModal.tsx
src/components/ChooseRegionModal/ChooseRegionModal.types.ts
src/components/Search/Search.tsx
src/components/SearchList/SearchList.tsx
src/utils/truncateText.ts

Close #12 
- 카테고리 모달 마크업
- 지역 선택 모달 마크업
pull 이후 `npm ci` 부탁드립니다!

Feat: 카테고리, 지역 선택 모달 마크업

---

package-lock.json
package.json
src/App.tsx
src/api/config.ts
src/api/getRoomDetail.ts
src/api/getUserInfo.ts
src/components/Card/Card.styles.ts
src/components/Card/Card.tsx
src/components/Card/Card.types.ts
src/components/CustomForm/CustomForm.tsx
src/components/CustomForm/CustomFrom.types.ts
src/components/Orders/DiffUserInfoField/DiffUserInfoField.tsx
src/components/Orders/PaymentOptionsField/PaymentOptionsField.tsx
src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.tsx
src/components/Orders/PaymentSummary/PaymentSummary.styles.ts
src/components/Orders/PaymentSummary/PaymentSummary.tsx
src/components/Orders/ReservationInfo/ReservationInfo.styles.ts
src/components/Orders/ReservationInfo/ReservationInfo.tsx
src/components/Orders/TermsAgreementField/TermsAgreementField.styles.ts
src/components/Orders/TermsAgreementField/TermsAgreementField.tsx
src/components/Orders/UserInfoField/UserInfoField.styles.ts
src/components/Orders/UserInfoField/UserInfoField.tsx
src/hooks/useRoomDetailQuery.ts
src/hooks/useUserInfoQuery.ts
src/pages/payment/Payment.data.ts
src/pages/payment/Payment.styles.ts
src/pages/payment/Payment.tsx
src/pages/roomDetail/RoomDetail.data.ts
src/pages/roomDetail/RoomDetail.styles.ts
src/pages/roomDetail/RoomDetail.tsx

close #21 
- 결제 페이지 전체적인 마크업
- 차크라 ui와 React-Hook-From을 결합한 CustomForm 컴포넌트를 만들었습니다. 
- 유효성검사가 잘 되는지 테스트를 많이 안해봐서 아직 사용은 하지 말아주세요
- 마크업단계까지만 진행했고 결제 로직과 유효성 검사는 실제 api로 테스트해볼 예정입니다
장바구니 페이지에서 결제정보 ui와 비슷한게 `PaymentSummary` 컴포넌트인데 아직 공통화 작업을 못해서 구조랑 스타일만 가져가시면 될 것 같습니다. 이부분도 제가 공통화시키겠습니다.
npm ci 부탁드립니다!

Feat: 결제 페이지 마크업

---

src/api/config.ts
src/api/getSearchList.ts
src/api/login/LoginApi.ts
src/api/register/RegisterApi.ts
src/components/ChooseDateModal/ChooseDateModal.types.ts
src/components/Search/Search.tsx
src/components/SearchList/SearchList.tsx
src/components/SearchList/SearchList.types.ts
src/hooks/useSearchList.ts
src/pages/searchResult/SearchResult.tsx
src/utils/convertDateFormat.ts
src/utils/convertDateFormat2.ts
src/utils/convertDateFormat3.ts

Close #40 
- 검색 결과 페이지 API 호출 로직 구현
- request URL 변경
현재 401 에러를 뱉긴 하지만 request는 정상적으로 보내집니다...!
@im-na0 나영님 `refetch()` 사용한 로직들 검토 부탁드려요!

Feat, Refactor: 검색 결과 페이지 API 호출 로직 구현 및 request URL 변경

---

src/App.tsx
src/pages/reservationDetails/ReservationDetails.tsx
src/pages/reservations/Reservations.tsx

Close #30 
- 예약 내역 페이지 마크업
- 예약 상세 페이지 마크업
- 예약 내역이 없는 경우
- 예약 내역이 있는 경우

Design: 예약 내역 페이지 및 예약 상세 페이지 마크업

---

package-lock.json
package.json
src/api/getDistrictList.ts
src/api/getRegionList.ts
src/api/getSearchList.ts
src/api/getWishLIst.ts
src/components/ChooseRegionModal/ChooseRegionModal.styles.ts
src/components/ChooseRegionModal/ChooseRegionModal.tsx
src/components/ChooseRegionModal/ChooseRegionModal.types.ts
src/components/MyWishList/MyWishList.tsx
src/components/Search/Search.tsx
src/components/SearchList/SearchList.tsx
src/components/SearchList/SearchList.types.ts
src/hooks/useDistrictList.ts
src/hooks/useRegionList.ts
src/hooks/useSearchList.ts
src/hooks/useWishLIst.ts
src/main.tsx
src/pages/searchResult/SearchResult.tsx
src/recoil/checkInAndOutDate.ts
src/utils/convertDateFormat4.ts

Close #53 
- usesuspense query 적용 및 키 설정, 카테고리 분류 수정
- 지역 정보 데이터 API 연동 및 스크롤시 totalPage값 불러오기
- 스크롤시 debounce 기능 추가
- region 선택시 모달 꺼지는 현상 수정
- WishList 페이지 API 호출 버그 수정
- warning 제거
- Search, SearchList 컴포넌트 형제 컴포넌트로 변경
- 검색어 입력시 refetch되는 현상 수정
- 검색 결과, 위시리스트 API 연동 테스트 완료하였습니다! 확인하시고 이상 있으면 말씀 주세요!
- Search, SearchList 컴포넌트 사이에 불필요한 렌더링이 일어나 부모 -> 형제 컴포넌트 관계로 변경했습니다!

Refactor, Fix: 검색 결과 페이지 리팩토링 및 에러 핸들링

---

src/api/login/LoginApi.ts
src/api/register/RegisterApi.ts
src/components/Layout/Header/Header.tsx
src/components/Login/LoginForm.tsx
src/components/Register/RegisterForm.tsx

Close #70 
로컬 테스트를 위한 로컬스토리지 값(엑세스토큰) 추가
``` js
const data = localStorage.getItem('access-token');
console.log(data) // 'access-token'값 출력

로컬 테스트를 위한 로컬스토리지 값(엑세스토큰) 추가

---

src/api/config.ts
src/api/deleteLike.ts
src/api/postLike.ts
src/components/ChooseDateModal/ChooseDateModal.tsx
src/components/ChooseRegionModal/ChooseRegionModal.styles.ts
src/components/ChooseRegionModal/ChooseRegionModal.tsx
src/components/ChooseRegionModal/ChooseRegionModal.types.ts
src/components/MyWishList/MyWishList.tsx
src/components/SearchList/SearchList.tsx
src/components/SearchList/SearchList.types.ts
src/hooks/useSearchList.ts
src/hooks/useSearchListMutation.ts
src/pages/searchResult/SearchResult.tsx

Close #64 
- 좋아요 기능 API 연동
- 지역선택모달 warning 해결
기능구현은 완료되었지만, 현재 토큰값을 쿠키에서 불러오지 못하여 post 요청시 500에러가 발생합니다.

Feat, Fix: 좋아요 기능 API 연동 및 warning 해결

---

src/components/MyWishList/MyWishList.tsx
src/components/SearchList/SearchList.tsx
src/pages/payment/Payment.tsx
src/utils/getAuthLocalStorage.ts

#63
```typescript
const {accessTokenCookie, headers} = getAuthLocalStorage()
``` 
이렇게 사용하시면 됩니다

Feat: 토큰값 로컬스토리지에서 받아오는 함수 구현

---

src/App.tsx
src/pages/notFound/NotFound.styles.tsx
src/pages/notFound/NotFound.tsx

close #82 
- 예정된 작업이 끝나 404 not found 페이지 제작했습니다,,!

Feat: 404 페이지 추가

---

src/components/Search/Search.tsx
src/components/Search/Search.types.ts
src/components/SearchList/SearchList.tsx
src/components/SearchList/SearchList.types.ts
src/main.tsx
src/pages/searchResult/SearchResult.tsx
src/recoil/searchStates.ts
src/theme/Fonts.tsx
src/theme/index.ts

Close #80 
- searchList 컴포넌트 region 설정
- 폰트 설정

Feat, Design: searchList 컴포넌트 region 설정 및 폰트 설정

---

src/components/MyWishList/MyWishList.tsx
src/components/SearchList/SearchList.tsx

Close #86
WishList Mutation 로직 변경

Refactor: WishList Mutation 로직 변경

---

src/components/ChooseDateModal/ChooseDateModal.tsx
src/components/ProductDetail/ChooseDetail/ChooseDetail.tsx
src/components/ProductDetail/WishListButton/WishListButton.tsx
src/components/ProductDetail/WishListButton/WishListButton.types.ts

- 날짜 선택 모달 마크업 및 에러 수정
- ChooseDetail 컴포넌트 에러 수정
- 위시리스트 API 연동

Feat: 에러 해결 및 마크업 수정

---

package-lock.json
package.json
src/App.tsx
src/components/AgreementModal/AgreementModalForm.tsx
src/components/Login/LoginForm.tsx
src/components/MyWishList/MyWishList.tsx
src/components/ProductDetail/WishListButton/WishListButton.tsx
src/components/Register/RegisterForm.tsx
src/components/Search/Search.tsx
src/components/SearchList/SearchList.tsx
src/components/ShoppingCart/ShoppingCartComp.tsx
src/hooks/useWishMutation.ts
src/main.tsx
src/pages/notLogin/NotLogin.tsx
src/utils/authCheck.ts

Close #91 
Swal alert toast로 교체
@YongYong21 용희님 페이지 확인 한번 부탁드립니다!

Refactor: Swal alert toast로 교체

---

src/api/getSearchList.ts
src/components/Main/AccommodationGridView/AccommodationGridView.tsx
src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
src/utils/sliceAccommodationName.ts

close #88 
기존에 에러나던 숙소 조회 API 로직에 맞게 수정했습니다.
(null 값으로 조회하지 않고 아예 쿼리를 보내지 않는 방식으로 수정)

Fix: 숙소 조회 API 로직 수정

---

src/api/accomodation/postCart.ts
src/components/ProductDetail/ChooseDetail/ChooseDetail.tsx
src/components/ProductDetail/ChooseRoom/ChooseRoom.tsx
src/components/ProductDetail/ChooseRoom/ChooseRoom.types.ts
src/components/ProductDetail/Image/Image.tsx
src/hooks/useCartMutation.ts
src/pages/productDetail/ProductDetail.tsx

- Image 컴포넌트 마크업 수정
- 장바구니 추가 API useMutation 적용

Refactor: 장바구니 추가 API useMutation 적용

---

src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
src/components/MyWishList/MyWishList.tsx
src/components/Rooms/RoomCarousel/RoomCarousel.tsx
src/components/SearchList/SearchList.tsx
src/pages/reservationDetails/ReservationDetails.tsx
src/pages/reservations/Reservations.tsx

Close #98 
- lazy loading 기능 추가
@im-na0 나영님 검토 부탁드려욤

Refactor: lazy loading 기능 추가

---

src/api/getCompletedPaymentInfo.ts

#106
- 결제완료 시 요청되는 엔드포인트를 수정했습니다.

Fix: 결제완료 엔드포인트 수정

---

src/components/Orders/RoomInfo/RoomInfo.tsx
src/components/Orders/RoomInfo/RoomInfo.types.ts
tsconfig.json

#106 
- 결제완료 페이지 룸 타입 수정 했습니다!

Fix: 결제완료 페이지 룸 타입 수정

---

src/components/Search/Search.tsx
src/components/SearchList/SearchList.tsx

Close #110 
검색 결과 페이지 url 전달 에러 수정

Fix: 검색 결과 페이지 url 전달 에러 수정

---

src/components/Main/AccommodationGridView/AccommodationGridView.tsx
src/components/Main/AccommodationSingleView/AccommodationSingleView.styles.ts
src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx

close #112 
- 메인 페이지 데이터 없어서 오류 발생 -> 변경된 데이터에 맞게 업데이트

Fix: 메인 페이지 데이터 없어서 발생하는 오류 수정

---

src/components/Main/AccommodationGridView/AccommodationGridView.styles.ts
src/components/Main/AccommodationGridView/AccommodationGridView.tsx
src/components/Main/AccommodationSingleView/AccommodationSingleView.styles.ts
src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx

close #99 
- 메인 페이지 세부 디자인 수정
- 캐러셀 버튼 위치 및 스타일 수정
- 타이틀 & 설명 마진 수정
- 그리드 아이템 커서 포인트로 수정
- 카테고리 메뉴 문구 수정

Design: 메인 페이지 세부 디자인 수정

---

src/api/accomodation/getRoomList.ts
src/components/ProductDetail/ChooseDetail/ChooseDetail.tsx
src/components/ProductDetail/ChooseDetail/ChooseDetail.types.ts
src/components/ProductDetail/ChooseRoom/ChooseRoom.tsx
src/components/ProductDetail/ChooseRoom/ChooseRoom.types.ts
src/components/ProductDetail/WishListButton/WishListButton.tsx
src/hooks/useRoomListQuery.ts
src/hooks/useWishList.ts
src/pages/productDetail/ProductDetail.tsx
src/utils/convertDateFormat.ts

Fix: 숙소 상세페이지 API 호출 에러 수정

---

src/components/Orders/RoomInfo/RoomInfo.tsx
src/components/Orders/RoomInfo/RoomInfo.types.ts
src/components/Orders/TotalPaymentInfo/TotalPaymentInfo.tsx
src/hooks/useCompletedPaymentQuery.ts
src/pages/completePayment/CompletePayment.tsx
src/pages/payment/Payment.tsx

Fix: 결제완료 페이지 데이터 안뜨는 거 수정

---

src/components/ChooseDateModal/ChooseDateModal.tsx
src/components/ChooseRegionModal/ChooseRegionModal.tsx
src/components/MyWishList/MyWishList.tsx
src/components/Search/Search.tsx
src/components/SearchList/SearchList.tsx
src/hooks/useWishList.ts
src/pages/searchResult/SearchResult.tsx
src/pages/wishList/WishList.tsx
src/recoil/searchStates.ts

Close #115 
- 태그 디자인 변경
- Build시 Warning 해결
- 검색 결과 페이지 검색 결과 없을 때 처리 및 가격 format 형식 변경

Fix, Design: 검색결과페이지 2차 에러핸들링

---

src/components/ProductDetail/ChooseDetail/ChooseDetail.tsx
src/components/ProductDetail/ChooseRoom/ChooseRoom.tsx
src/components/ProductDetail/WishListButton/WishListButton.tsx
src/components/SearchList/SearchList.tsx
src/pages/productDetail/ProductDetail.tsx

- 숙소 이름 필터링
- 필터링 결과가 없는 경우 마크업 추가
- 객실 재고가 없는 경우 마크업 추가
- 위시리스트 버튼 경고창 추가
- 객실 가격 priceFormatter 적용

Design: 숙소 상세 페이지 세부 마크업 수정

---

src/api/accomodation/postPayment.ts
src/components/ProductDetail/ChooseRoom/ChooseRoom.tsx
src/components/ProductDetail/ChooseRoom/ChooseRoom.types.ts
src/components/ProductDetail/Map/Map.tsx
src/hooks/usePaymentMutation.ts

- 바로 결제하기 API 연동
- Map 컴포넌트 경고 임시 수정

Feat: 바로 결제하기 API 연동

---

src/components/Main/AccommodationSingleView/AccommodationSingleView.styles.ts

Fix: 캐러셀 크기 고정 값으로 수정

---

src/api/getSearchList.ts
src/components/MyWishList/MyWishList.tsx
src/components/Search/Search.tsx
src/components/SearchList/SearchList.tsx
vercel.json

Close #133 
- vercel 설정파일 추가
- 위시리스트 디자인 수정
- 로그인 안했을때 하트 색깔 바뀌는 현상 수정
- 주석 제거

Env, Design, Fix, Chore: 위시리스트 페이지 디자인 변경 및 배포 설정 변경

---

src/components/Main/AccommodationSingleView/AccommodationSingleView.styles.ts
src/components/Main/MainCarousel/MainCarousel.styles.ts

#124 
캐러셀 slick 스타일 수정했습니다. 최선을 다 하겠습니다....

Fix: 캐러셀 slick 스타일 수정

---

src/api/deleteWish.ts
src/api/getSearchList.ts
src/api/getWishList.ts
src/api/postWish.ts
src/components/MyWishList/MyWishList.tsx
src/components/Search/Search.tsx
src/components/SearchList/SearchList.tsx
src/hooks/useSearchList.ts
src/hooks/useWishList.ts
src/hooks/useWishMutation.ts

Close #139
- 좋아요 초깃값 설정 및 상태 변화 구현
- refetch시 리렌더링 되지 않는 현상 수정

Fix: 좋아요 post, delete시 헤더 안담기는 오류 수정

---

src/api/getMemberInfo.ts
src/components/Layout/Footer/Footer.styles.ts
src/components/Layout/Footer/Footer.tsx
src/components/Layout/Header/Header.styles.ts
src/components/Layout/Header/Header.tsx
src/components/Layout/Header/HeaderInput.tsx

Close #143 
헤더 푸터 리펙토링
엑세스토큰 로컬스토리지 -> 쿠키 값 참조
html, css 수정

리펙토링: 헤더 푸터 

---

src/components/Main/AccommodationGridView/AccommodationGridView.tsx
src/components/Main/AccommodationGridView/AccommodationGridView.types.ts
src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
src/components/Main/AccommodationSingleView/AccommodationSingleView.types.ts
src/components/Main/MainCategoryMenu/MainCategoryMenu.styles.ts
src/pages/main/Main.tsx
src/utils/printCategory.ts

close #145 
멘토님 코멘트, 메인 페이지에서 리팩토링 해야 할 부분들 **에러 바운더리 적용** 제외하고 완료했습니다.
- 메인 페이지 리팩토링  
- 콘솔 error 제거
- access token 쿠키로 수정
**충돌이나 에러 발생 가능성 있는 파일들 참고 부탁드립니다 ‼️**
`useSearchList` 사용했습니다. useSearchList hook이 변경되었다면 에러 발생할 수 있습니다.   <br><br>  
용희님 PR 참고해서 header access token 부분 로컬 스토리지에서 useCookies 사용해서 사용하여 쿠키로 변경하였으나 merge 된 상태에서 확인해본 것이 아니라 에러 발생할 수 있습니다. (현재는 access token은 undefined로 나옵니다.)  <br><br>  
`convertDateFormat4` 사용했습니다. 날짜 포매터 함수 파일 합치거나 제거하시면 에러 발생할 거라서 convertDateFormat4에 맞는 함수 새로 적용해주면 될 것 같습니다.  <br><br>  
👉🏻 **이외에 충돌이나 에러 발생하는 부분 있으면 코드 임의로 수정해주셔도 됩니다. 감사합니다!**
👉🏻 **12월 8일 금요일, 12월 11일 월요일 휴가 사용으로 회의 참석이 어렵습니다. 제가 참고해야 할 사항이나 해야 할 일들 회의록에 적어주시면 감사드리겠습니다. 다녀와서 회의록 확인 후 할 작업들 얼른 들어가겠습니다!**
👉🏻 **이외에 궁금한 점이나 에러 사항 있으면 해당 PR에 코멘트 남겨주시면 확인하겠습니다:)**

Refactor: 메인 페이지 리팩토링

---

src/api/ApiResponse.type.ts
src/api/login/LoginApi.ts
src/api/register/RegisterApi.ts
src/components/Login/LoginForm.tsx
src/components/Register/RegisterForm.tsx
src/hooks/login/useLoginMutation.ts
src/hooks/register/useRegisterMutation.ts

Close #148 
refactor: 로그인, 회원가입
제레릭 타입 추가,
로컬스토리지 -> 쿠키값 참조

refactor: 로그인, 회원가입

---

src/components/AgreementModal/AgreementModalForm.tsx
src/components/CustomForm/CustomButton.tsx
src/components/CustomForm/CustomFrom.styles.ts
src/components/Layout/Footer/Footer.styles.ts
src/components/Layout/Layout.styles.ts
src/components/Layout/Layout.tsx
src/components/Orders/PaymentOptionsForm/PaymentOptionsForm.styles.ts
src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.tsx
src/components/Orders/TermsAgreementForm/TermsAgreementForm.tsx
src/styles/GlobalStyles.ts
src/theme/index.ts

close #171
- 야놀자 대표색을 primary로 변수화
- Chakra UI default colorScheme를 primary 색상으로 사용: 모든 차크라 ui 컴포넌트 색상이 primary 컬러를 사용하도록 했습니다.
- Footer랑 Content width 가 안맞던거 수정했습니다.
숙소 상세 페이지 예시)

Design: 컬러 팔레트 사용 & default colorScheme 적용

---

src/components/Layout/Header/Header.tsx
src/components/ShoppingCart/ShoppingCartComp.tsx
src/hooks/login/useLoginMutation.ts

close #178 
요청하신 로컬 스토리지 엑세스토큰값 추가했습니다.

fix: add 로컬 스토리지 추가

---

src/App.tsx
src/components/Main/AccommodationGridView/AccommodationGridView.tsx
src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
src/components/Main/MainSkeleton/AccommodationGridViewSkeleton.tsx
src/components/Main/MainSkeleton/AccommodationSingleViewSkeleton.tsx
src/components/Main/MainSkeleton/MainCarouselSkeleton.tsx
src/components/Main/MainSkeleton/MainCategoryMenuSkeleton.tsx
src/components/Main/MainSkeleton/MainSkeleton.styles.ts
src/components/Main/MainSkeleton/MainSkeleton.tsx
src/components/SearchResultSkeleton/SearchInputSkeleton.tsx
src/components/SearchResultSkeleton/SearchListSkeleton.tsx
src/components/SearchResultSkeleton/SearchResultSkeleton.styles.ts
src/components/SearchResultSkeleton/SearchResultSkeleton.tsx

close #175 
메인 페이지, 검색 결과 페이지에 스켈레톤 UI 적용했습니다.

Feat: 메인 페이지, 검색 결과 페이지 Skeleton UI 추가

---

src/components/SearchList/SearchList.tsx
src/hooks/login/useLoginMutation.ts
src/tests/searchResult.spec.ts
src/tests/wishList.spec.ts

Close #184 
- 좋아요 추가, 삭제 기능 테스트코드 수정
- 좋아요 버튼 클릭 시 동일한 요청 가는 오류 해결
- 위시리스트 페이지 테스트코드 작성
@YongYong21 처음 로그인 이후 메인페이지로 이동해도 헤더에 로그인/회원가입 버튼이 활성화되어있습니다. 수정 필요할것같아요!

Test: 위시리스트 페이지 테스트코드 작성

---

src/api/login/LoginApi.ts
src/api/register/RegisterApi.ts
src/api/shoppingCart/shoppingCartApi.ts
src/components/Layout/Header/Header.tsx
src/components/ShoppingCart/ShoppingCartComp.tsx
src/hooks/cart/useDeleteCartMutation.ts
src/hooks/cart/useQuantityCartMutation.ts
src/hooks/cart/useShoppingCartList.ts
src/hooks/login/useLoginMutation.ts
src/tests/login.spec.ts
src/tests/register.spec.ts
src/tests/shoppingCart.spec.ts

close #170
axios instance 적용
로그인시 헤더가 바뀌지 않는 문제 해결.
테스트 코드 파일은 무시해주세요. 아직 완성된 코드가 아닙니다.

axios instance 적용 오류 해결.

---

src/api/axiosInstance.ts

Close #189 
withCredentials 속성 전역으로 설정

Fix: withCredentials 속성 전역으로 설정

---

src/components/AgreementModal/AgreementModalForm.tsx
src/components/Layout/Header/Header.tsx
src/components/Login/LoginForm.tsx
src/components/Register/RegisterForm.tsx
src/components/ShoppingCart/ShoppingCartComp.tsx
src/tests/login.spec.ts
src/tests/register.spec.ts
src/tests/shoppingCart.spec.ts

테스트 코드 수정
테스트코드 수정
로그인 페이지에 쿠키값 참조부분이 남아있어서 로컬스토리지로 수정하고 주석처리했습니다.
ShoppingCart 테스트할 때, 장바구니에 최소 한 개이상의 객실이 있어야 테스트가 가능해요..
ShoppingCart 테스트 코드가 에러는 나지 않지만 fail이 뜨네요... 흠..

테스트 파일 추가 및 수정

---

src/components/SearchList/SearchList.tsx
src/components/SearchList/SearchList.types.ts
src/pages/productDetail/ProductDetail.tsx
src/utils/isPrintable.tsx

Close #197 
- gpt api 연동
`npm i` 해주세요!

Feat: gpt api 연동

---

src/components/AgreementModal/AgreementModalForm.tsx
src/components/Register/RegisterForm.tsx
src/components/ShoppingCart/ShoppinCart.types.ts
src/components/ShoppingCart/ShoppingCart.styles.ts
src/components/ShoppingCart/ShoppingCartComp.tsx
src/components/ShoppingCart/ShoppingCartList.tsx
src/hooks/cart/useDeleteCartMutation.ts
src/hooks/login/useLoginMutation.ts
src/hooks/register/useRegisterMutation.ts
src/tests/register.spec.ts
src/tests/shoppingCart.spec.ts

Close #170 
palywright 테스트 코드 수정 및 드래그앤드롭 기능 추가. / 회원가입 플로우 수정.
드래그가 되는 모습이 캡처에서는 보이지가 않네요
플로우 수정에 맞게 회원가입 테스트코드 수정했습니다.

palywright 테스트 코드 수정 및 드래그앤드롭 기능 추가. / 회원가입 플로우 수정.

---

src/components/ProductDetail/ChooseDetail/ChooseDetail.tsx
src/hooks/useReservationsMutation.ts
src/tests/productDetail.spec.ts
src/tests/reservations.spec.ts

- 숙소 상세 페이지 테스트 코드 작성
- 예약 페이지 테스트 코드 작성

Test: 테스트 코드 작성

---

README.md

Readme 테스트 계정 추가 및 예약 내역 취소 추가.
Readme 테스트 계정 추가 및 예약 내역 취소 추가.

Readme 테스트 계정 추가 및 예약 내역 취소 추가.
